### PR TITLE
add tab completion for git commands

### PR DESCRIPTION
**Pull request by cbroeren**

### CODE REVIEW

**Comment by Florisvanvoorst** [comment]
:+1:

**Comment by martndemus** [comment]
[These lines](https://github.com/cbroeren/laptop-install/blob/add-git-completion/dotfiles/bash_profile#L23-L26) should take care of that

**Comment by cbroeren** [comment]
Sadly enough... they don't...

**Comment by InteNs** [comment]
Yeah I already have tab completion for git

**Comment by martndemus** [comment]
Is `bash-completion2` installed with brew?

**Comment by InteNs** [comment]
Rerun laptop install maybe

**Comment by martndemus** [comment]
Have you tried `reload` :trollface:

**Comment by cbroeren** [comment]
Very funny... @InteNs this is a new laptop, so a new laptop-install. @martndemus Ofcourse I have tried reloading, reopening terminal and even restarting my laptop...

**Comment by martndemus** [comment]
What does `bash --version` report?

**Comment by cbroeren** [comment]
Also it isn't working for @michieltjuh11 and @Florisvanvoorst too

**Comment by cbroeren** [comment]
bash --version returns

GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.0.0)
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

**Comment by martndemus** [comment]
It worked for me out of the box when I ran the install a few weeks ago :trollface:

**Comment by cbroeren** [comment]
I ran the install 2 days ago, and @Florisvanvoorst and @michieltjuh11 ran it some weeks ago, even @Florisvanvoorst did a new try just now and it didn't work.

Suggestions?

**Comment by martndemus** [comment]
Does the folder `/usr/local/share/bash-completion/bash_completion` exist?

**Comment by martndemus** [comment]
Will it autocomplete for any other things? (except for paths and commands itself)

**Comment by cbroeren** [comment]
No, there isn't even a bash-completion folder in the share folder

**Comment by martndemus** [comment]
Well there is your problem.

**Comment by martndemus** [comment]
try `brew install bash-completion2`

**Comment by cbroeren** [comment]
That fixed it. Any idea why it wasn't installed from the install.sh?

**Comment by martndemus** [comment]
Nope. Should have.

**Pull request closed without merging**
